FROM python:3.7-slim

WORKDIR /app
ADD python/ /app/python/
ADD requirements.txt /app/
ADD __init__.py /app/

RUN apt update && apt install -y curl
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py
RUN pip3 install -r requirements.txt

ENTRYPOINT ["python", "python/eventhandler.py", "&> /tmp/log.txt"]